baseURL: https://CLARKBENHSM.github.io
languageCode: en-us
title: Clark Benham, introduction to
theme: "PaperMod"
params:
    homeInfoParams:
        title:
        content: |
          <img src="images/screwtape_pleasures.jpg">

    socialIcons:
        - name: "github"
          url: "https://github.com/CLARKBENHAM/"
        - name: "twitter"
          url: "https://twitter.com/ClarkBenham2"
menu:
    main:
        - name: About
          url: about
          weight: 5
markup:
    goldmark:
      renderer:
        unsafe: true

